# Site settings
title: Chowdown
email: dan@danisaacs.net
description: The plain text recipe database for hackers
baseurl: "/cooking"
language: "en"
lang_direction: "ltr"
color: "#007FFF"
twitter_username: 
github_username:  di-dc

# Build settings
markdown: kramdown

permalink: /:title:output_ext

collections:
  components:
    output: true
  recipes:
    output: true

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
